apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          #imagem customizada criada
          image: php-app:latest #meuusergithub/biblioteca_php:1
          ports:
          #apache ou php embutido escutando na porta
            - containerPort: 80
---
#Service para expor o app php para fora do cluster
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  type: NodePort
  ports:
    - port: 80               #porta dentro do container
      targetPort: 80         #porta do container
      nodePort: 30080        #porta no host(mapeada)
  selector:
    app: php #conecta 